# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nexe Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      build: [1,2,3]
      include:
        - build: 1
          os: windows-latest
          node-version: 18.x
          platform: windows
          arch: x64
        - build: 2
          os: windows-latest
          node-version: 18.x
          platform: windows
          arch: x86
        - build: 3
          os: macos-12
          node-version: 18.x
          platform: macos
          arch: x64
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node build.js --target_platfrom ${{ matrix.platform }} --target-arch ${{ matrix.arch }}
