# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nexe Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [windows-x64, windows-x86, macos-x64]
        include:
          - build: windows-x64
            os: windows-latest
            node-version: 18.x
            platform: windows
            arch: x64
          - build: windows-x86
            os: windows-latest
            node-version: 18.x
            platform: windows
            arch: x86
          - build: macos-x64
            os: macos-12
            node-version: 18.x
            platform: macos
            arch: x64
    steps:
    - uses: actions/checkout@v3
	- uses: ilammy/setup-nasm@v1
    - uses: actions/setup-python@v4
      id: cp310
      with:
        python-version: '3.10'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node build.js --python_path ${{ steps.cp310.outputs.python-path }} --target_platfrom ${{ matrix.platform }} --target-arch ${{ matrix.arch }}
